stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/diabetes.csv
    outs:
    - data/raw/diabetes.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/diabetes.csv
    outs:
      - data/processed/x_test_diabetes.csv
      - data/processed/x_train_diabetes.csv
      - data/processed/y_test_diabetes.csv
      - data/processed/y_train_diabetes.csv
      - saved_models/scalarr.joblib

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/x_test_diabetes.csv
      - data/processed/x_train_diabetes.csv
      - data/processed/y_test_diabetes.csv
      - data/processed/y_train_diabetes.csv
      - src/train_and_evaluate.py
    outs:
      - saved_models/model.joblib
