base:
  project: diabetes-project
  random_state: 355
  target_col: Outcome

data_source:
  s3_source: data_given/diabetes.csv

load_data:
  raw_dataset_csv: data/raw/diabetes.csv

split_data:
  x_train_path: data/processed/x_train_diabetes.csv
  y_train_path: data/processed/y_train_diabetes.csv
  x_test_path: data/processed/x_test_diabetes.csv
  y_test_path: data/processed/y_test_diabetes.csv
  test_size: 0.2

model_dir: saved_models

webapp_model_dir: prediction_service/model.joblib
webapp_scalar_dir: prediction_service/scalarr.joblib